server:
  port: 8080

spring:
  config:
    import:
      - token.yml
      - scrap.yml
      - aes.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

springdoc:
  swagger-ui:
    path: /3o3/swagger.html